import { NextRequest, NextResponse } from "next/server";
import type { FlattenMaps } from "mongoose";

import connectDB from "@/lib/mongodb";
import Event, { type IEvent } from "@/database/event.model";

/** Matches slugs generated by the Event model's generateSlug helper */
const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

type RouteContext = {
  params: Promise<{ slug: string }>;
};

type EventLean = FlattenMaps<IEvent> & Required<{ _id: IEvent["_id"] }>;

type SlugValidationResult =
  | { valid: true; slug: string }
  | { valid: false; message: string };

/**
 * Normalizes and validates a URL slug before querying the database.
 */
function validateSlug(rawSlug: string | undefined): SlugValidationResult {
  if (rawSlug === undefined || rawSlug.trim() === "") {
    return { valid: false, message: "Slug is required" };
  }

  let decodedSlug: string;

  try {
    decodedSlug = decodeURIComponent(rawSlug);
  } catch {
    return { valid: false, message: "Slug contains invalid URL encoding" };
  }

  const slug = decodedSlug.trim().toLowerCase();

  if (!slug) {
    return { valid: false, message: "Slug is required" };
  }

  if (slug.length > 100) {
    return { valid: false, message: "Slug exceeds maximum length" };
  }

  if (!SLUG_PATTERN.test(slug)) {
    return { valid: false, message: "Slug format is invalid" };
  }

  return { valid: true, slug };
}

export async function GET(
  _request: NextRequest,
  context: RouteContext,
): Promise<NextResponse> {
  try {
    const { slug: rawSlug } = await context.params;
    const validation = validateSlug(rawSlug);

    if (!validation.valid) {
      return NextResponse.json({ message: validation.message }, { status: 400 });
    }

    await connectDB();

    const event = await Event.findOne({ slug: validation.slug })
      .select("-__v")
      .lean<EventLean>();

    if (!event) {
      return NextResponse.json({ message: "Event not found" }, { status: 404 });
    }

    return NextResponse.json(
      { message: "Event fetched successfully", event },
      { status: 200 },
    );
  } catch (error) {
    console.error("[GET /api/events/[slug]]", error);

    return NextResponse.json(
      {
        message: "Failed to fetch event",
        error: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}
